"""empty message

Revision ID: 33711cbbe044
Revises: 79869a92d759
Create Date: 2022-07-09 00:53:12.441796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33711cbbe044'
down_revision = '79869a92d759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('birth_year', sa.String(length=256), nullable=True),
    sa.Column('eye_color', sa.String(length=256), nullable=True),
    sa.Column('gender', sa.String(length=256), nullable=True),
    sa.Column('hair_color', sa.String(length=256), nullable=True),
    sa.Column('height', sa.String(length=256), nullable=True),
    sa.Column('mass', sa.String(length=256), nullable=True),
    sa.Column('skin_color', sa.String(length=256), nullable=True),
    sa.Column('homeworld', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('Character')
    op.drop_table('user')
    op.create_unique_constraint(None, 'Favorites', ['id'])
    op.create_unique_constraint(None, 'Users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Favorites', type_='unique')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('_password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.create_table('Character',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Character_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('birth_year', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('eye_color', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('hair_color', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('height', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('mass', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('skin_color', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('homeworld', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Character_pkey')
    )
    op.drop_table('Characters')
    # ### end Alembic commands ###
