"""empty message

Revision ID: 79869a92d759
Revises: 9d19a529aaf7
Create Date: 2022-07-09 00:44:22.207761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79869a92d759'
down_revision = '9d19a529aaf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('birth_year', sa.String(length=256), nullable=True),
    sa.Column('eye_color', sa.String(length=256), nullable=True),
    sa.Column('gender', sa.String(length=256), nullable=True),
    sa.Column('hair_color', sa.String(length=256), nullable=True),
    sa.Column('height', sa.String(length=256), nullable=True),
    sa.Column('mass', sa.String(length=256), nullable=True),
    sa.Column('skin_color', sa.String(length=256), nullable=True),
    sa.Column('homeworld', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('user_name', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fave_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('user', sa.Column('_password', sa.String(length=128), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('user', '_password')
    op.drop_table('Favorites')
    op.drop_table('Users')
    op.drop_table('Character')
    # ### end Alembic commands ###
