"""empty message

Revision ID: d1e89151f07d
Revises: efe3580cf1a4
Create Date: 2022-07-16 20:45:52.052822

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1e89151f07d'
down_revision = 'efe3580cf1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('favorites', postgresql.ARRAY(sa.VARCHAR(length=256)), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
