"""empty message

Revision ID: eb1248afa89a
Revises: 33711cbbe044
Create Date: 2022-07-09 23:40:52.043549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1248afa89a'
down_revision = '33711cbbe044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Characters', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Characters', type_='unique')
    # ### end Alembic commands ###
