"""empty message

Revision ID: efe3580cf1a4
Revises: eb1248afa89a
Create Date: 2022-07-15 23:33:34.009141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe3580cf1a4'
down_revision = 'eb1248afa89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('favorites', sa.ARRAY(sa.String(length=256)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'favorites')
    # ### end Alembic commands ###
