"""empty message

Revision ID: f197fa994679
Revises: d1e89151f07d
Create Date: 2022-07-16 20:53:30.012816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f197fa994679'
down_revision = 'd1e89151f07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    # ### end Alembic commands ###
